### ISSUE TITLE
Validation is failing for target_resource when sending KeyVault id

### ISSUE THREAD

**Issue by andrew-stephens-insight** [claranet/terraform-azurerm-private-endpoint#1]
In your example for KeyVault private endpoint, the validation fails for target_resource due to a regex issue with the KeyVault resource id, which is valid.

I believe it is because my resource group has underscores (which is valid naming) instead of dashes.
The referenced KeyVault exists and was creating using your KeyVault module.

part of the regex:  \\/(resourceGroups)\\/([A-Za-z0-9\\-]+)
my example rg name:  my_rg_name

My error message:
Error: Invalid value for variable

  on keyvault.tf line 35, in module "kv_private_endpoint":
  35:   target_resource  = module.key_vault.key_vault_id
    ├────────────────
    │ var.target_resource is "/subscriptions/<my sub>/resourceGroups/my_rg_name/providers/Microsoft.KeyVault/vaults/my-kv-name"

The `target_resource` variable must be a Private Link Service Alias or a
resource ID.

This was checked by the validation rule at
.terraform/modules/kv_private_endpoint/variables.tf:52,3-13.

**Comment by jmapro** [comment]
Hello @andrew-stephens-insight ,

Thanks for opening this issue. We're working on a fix and keep you posted when it will be available.

**Comment by jmapro** [comment]
Hello @andrew-stephens-insight !

a new version (v6.3.1) was just released with the fix.
