### ISSUE TITLE
[BUG] Error on private-dns-zone when tags is empty

### ISSUE THREAD

**Issue by fdmsantos** [claranet/terraform-azurerm-private-endpoint#2]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.7

### AzureRM Provider Version

3.74

### Affected Resource(s)/Data Source(s)

private dns zone module

### Terraform Configuration Files

```hcl
default_tags_enabled = false
extra_tags           = {}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/bot.private_endpoint/modules/private-dns-zone/locals-tags.tf line 11, in locals:
│   11:     for key in chunklist(keys(local.merged_tags), 14)[0] : key => lookup(local.merged_tags, key)
│     ├────────────────
│     │ local.merged_tags is empty map of string
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
```

**Comment by zfiel** [comment]
Hello @fdmsantos ,

Thank you for opening this issue. We're working on a fix and keep you posted when it will be available.

**Comment by Shr3ps** [comment]
Fixed in https://github.com/claranet/terraform-azurerm-private-endpoint/releases/tag/v7.0.2
🚀
